import "server-only";

import { GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";

/**
 * R2 credentials are server-only — no NEXT_PUBLIC_ prefix, so they can never
 * reach the browser bundle. The bucket stays private; the browser never holds
 * a credential, only short-lived read URLs this server signs for it.
 */
const accountId = process.env.R2_ACCOUNT_ID ?? "";
const accessKeyId = process.env.R2_ACCESS_KEY_ID ?? "";
const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY ?? "";

export const R2_BUCKET = process.env.R2_BUCKET ?? "";

export const isR2Configured = Boolean(accountId && accessKeyId && secretAccessKey && R2_BUCKET);

let client: S3Client | null = null;

export function r2(): S3Client {
  if (!isR2Configured) throw new Error("R2 is not configured.");
  client ??= new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId, secretAccessKey },
  });
  return client;
}

/** Every object lives under the owner's uid. Nothing else is addressable. */
export function userPrefix(uid: string) {
  return `photos/${uid}/`;
}

/** Generated previews live under the same uid prefix, so ownsKey covers them. */
export function previewKey(uid: string, id: string, ext = "png") {
  return `${userPrefix(uid)}previews/${id}.${ext}`;
}

export function ownsKey(uid: string, key: string) {
  return (
    typeof key === "string" &&
    key.startsWith(userPrefix(uid)) &&
    !key.includes("..") &&
    key.length <= 200
  );
}

/** Reads one object's bytes. The caller must have checked ownership first. */
export async function getObjectBytes(key: string) {
  const result = await r2().send(new GetObjectCommand({ Bucket: R2_BUCKET, Key: key }));
  const bytes = await result.Body!.transformToByteArray();
  return { bytes, contentType: result.ContentType ?? "image/jpeg" };
}

/** Stores generated bytes. The caller owns the key by construction. */
export async function putObjectBytes(key: string, bytes: Uint8Array, contentType: string) {
  await r2().send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: key,
      Body: bytes,
      ContentType: contentType,
      // Previews are derived data — safe to regenerate, cheap to cache.
      CacheControl: "private, max-age=31536000, immutable",
    }),
  );
  return key;
}
